### PR TITLE
change fileretrievaldynamic to NetworkPartition

### PR DESCRIPTION
**Pull request by vandot**

### CODE REVIEW

**Comment by vandot** [comment]
@svetomir this PR is not good, discovered bug in chaos-mesh for NetworkChaos, it can be only merged after that bug is fixed upstream

**Comment by zhouqiang-cl** [comment]
> @svetomir this PR is not good, discovered bug in chaos-mesh for NetworkChaos, it can be only merged after that bug is fixed upstream

Can you give a detail bug of chaos-mesh or file an issue in [here](https://github.com/chaos-mesh/chaos-mesh/issues/new/choose)? We will look into it and fix as soon as possible

**Comment by zhouqiang-cl** [comment]
Since Chaos Mesh have already join CNCF sandbox, we need to move it to chaos-mesh org, If update Chaos Mesh, please also update apiVersion to chaos-mesh.org/v1alpha1

**Comment by zhouqiang-cl** [comment]
We have refine the network partition, could you please update chaos mesh and test it again? @vandot 
Thank you very much

**Comment by vandot** [comment]
tested and commented here https://github.com/chaos-mesh/chaos-mesh/issues/763#issuecomment-671404255

**Pull request closed without merging**
