### PR TITLE
refactor: rename db-capacity flag to cache-capacity

### PR DESCRIPTION
**Pull request by anatollupacescu**

### CODE REVIEW

**Review by svetomir — APPROVED** [review]

**Comment by svetomir** [comment]
Lets not merge this PR, it will be obsolete after https://github.com/ethersphere/beekeeper/pull/146

**Comment by Eknir** [comment]
@anatollupacescu , this PR is still open, but when I check-out master `cache-capacity` is a flag. Can you tell me what's up?

**Comment by anatollupacescu** [comment]
> @anatollupacescu , this PR is still open, but when I check-out master `cache-capacity` is a flag. Can you tell me what's up?

In the beekeeper project there's only one mention of `cache-capacity` and that was added by @esadakar for the GC test.

This PR is for renaming all `db-capacity` occurrences in the beekeeper.

**Comment by svetomir** [comment]
Obsolete due to https://github.com/ethersphere/beekeeper/pull/146

**Pull request closed without merging**
